// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKKhy7nJD8pbVqe4L19OLC_5nmX-aVp_Y',
    appId: '1:780912636462:web:f27127b28c6789e773a5bf',
    messagingSenderId: '780912636462',
    projectId: 'crud-6f8eb',
    authDomain: 'crud-6f8eb.firebaseapp.com',
    storageBucket: 'crud-6f8eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZv4Y320E0zL1u-ItEqklHnS-p5JDFT0g',
    appId: '1:780912636462:android:28d466ab548472b373a5bf',
    messagingSenderId: '780912636462',
    projectId: 'crud-6f8eb',
    storageBucket: 'crud-6f8eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtfHxsRkVQUzFJhu3GQy4pUoiDJFqvfZI',
    appId: '1:780912636462:ios:e540e93c5e8587b873a5bf',
    messagingSenderId: '780912636462',
    projectId: 'crud-6f8eb',
    storageBucket: 'crud-6f8eb.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtfHxsRkVQUzFJhu3GQy4pUoiDJFqvfZI',
    appId: '1:780912636462:ios:e540e93c5e8587b873a5bf',
    messagingSenderId: '780912636462',
    projectId: 'crud-6f8eb',
    storageBucket: 'crud-6f8eb.appspot.com',
    iosBundleId: 'com.example.flutterAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKKhy7nJD8pbVqe4L19OLC_5nmX-aVp_Y',
    appId: '1:780912636462:web:f23fbc3163694eee73a5bf',
    messagingSenderId: '780912636462',
    projectId: 'crud-6f8eb',
    authDomain: 'crud-6f8eb.firebaseapp.com',
    storageBucket: 'crud-6f8eb.appspot.com',
  );
}
